spring:
  datasource:
    url: jdbc:mysql://47.105.70.96:3307/atongflyway?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "123456"

  flyway:
    baseline-on-migrate: true
    locations:
      - "classpath:/db"
server:
  port: 8091

profiles:
  active: "@profiles.active@"