spring:
  datasource:
    url: jdbc:mysql://192.168.4.4:3306/pookie?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "0.123abc"

  flyway:
    baseline-on-migrate: true
    locations:
      - "classpath:/db"
server:
  port: 8091

profiles:
  active: "@profiles.active@"